nome = input('digite um funcionario: ')
empresa = input('digite a instituição: ')
qtde_funcionarios =int(input('digite a qtde de funcionarios: '))
mediaMensalidade = float(input('digite a média da mesalidade: '))
print (nome + ' trabalha na empresa ' + empresa)
print ('possui: ', qtde_funcionarios, ' funcionarios.')
print('A media da mensalidade é de: ' + str(mediaMensalidade))
print('==============Verifique os tipos de dados abaixo:=================')
print('O tipo de dado da variavel [nome] é: ',type (empresa))
print('O tiipo de dado da variavel [empresa] é ',type(empresa))
print('O tipo de dado da variavel [qtde_funcionario] é: ',type(qtde_funcionarios))
print('O tipo de dado da variavel [mediaMensalidade] é: ', type(mediaMensalidade))
